services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_bullmq_test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bullmq_test_db
    ports:
      - "6000:5432"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

volumes:
  postgres_data_volume:
