name: Connect to EC2 and create folder

on:
  push:
    branches:
      - main
      - add_book_model

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo "welcome"

  main_branch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: run hello
        run: echo "hellllllllo frommm mainnnn"

  add_book_model_branch:
    if: github.ref == 'refs/heads/add_book_model'
    runs-on: ubuntu-latest
    steps:
      - name: run tekoteko
        run: echo "techchcaskjdklasjdlkas"
