name: Connect to EC2 and create folder

on:
  push:
    branches:
      - main
      - add_book_model


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        run: echo  "welcome"

  maiin:
    if: github.ref == "ref/head/main"
    runs-on: ubuntu-latest
    steps:
      - name: run hello
        run: echo "hellllllllo frommm mainnnn"

  add_book_model_brannch:
    if: github.ref == "ref/head/add_book_model"
    runs-on: ubuntu-latest
    steps:
      - name: run tekoteko
        run: echo "techchcaskjdklasjdlkas"

 
